#
#  Copyright (c) 2023-2025 - Restate Software, Inc., Restate GmbH
#
#  This file is part of the Restate SDK for Python,
#  which is released under the MIT license.
#
#  You can find a copy of the license in file LICENSE in the root
#  directory of this repository or package, or at
#  https://github.com/restatedev/sdk-typescript/blob/main/LICENSE
#
"""
OpenAI-agents services used by the AI integration tests.
"""

from typing import Any

import restate
from restate import Context, ObjectContext, ObjectSharedContext, TerminalError
from pydantic import BaseModel

from agents import Agent, RunResult
from restate.ext.openai import (
    DurableRunner,
    durable_function_tool,
    restate_context,
    restate_object_context,
)

# A cheap model keeps cost negligible while still producing genuinely
# non-deterministic output, which is exactly what surfaces replay bugs.
MODEL = "gpt-4o-mini"


def generated_items(result: RunResult) -> list[dict[str, Any]]:
    """Return all messages, tool calls, and tool outputs generated by a run."""
    return [dict(item.to_input_item()) for item in result.new_items]


# --------------------------------------------------------------------------
# Chat / weather agent (tools + durable sessions + parallel tool calls)
# --------------------------------------------------------------------------


@durable_function_tool
async def get_weather(city: str) -> str:
    """Get the current weather for a given city.

    Args:
        city: The city to get the weather for.
    """

    async def call_weather_api() -> str:
        return f"The weather in {city} is sunny and 22 degrees Celsius."

    return await restate_object_context().run_typed("call weather api", call_weather_api)


weather_agent = Agent(
    name="Assistant",
    instructions=(
        "You are a concise assistant. When the user asks about the weather you MUST "
        "call the get_weather tool. Answer in one short sentence per city."
    ),
    model=MODEL,
    tools=[get_weather],
)


agent_object = restate.VirtualObject("AgentObject")


@agent_object.handler()
async def message(ctx: ObjectContext, prompt: str) -> list[dict[str, Any]]:
    """Send a single message to the agent, persisting conversation history."""
    result = await DurableRunner.run(weather_agent, prompt, use_restate_session=True)
    return generated_items(result)


@agent_object.handler(kind="shared")
async def get_session_items(ctx: ObjectSharedContext) -> list[dict[str, Any]]:
    """Return the durable OpenAI Agents session stored for this object key."""
    return await ctx.get("items", type_hint=list[dict[str, Any]]) or []


# --------------------------------------------------------------------------
# Terminal error propagation (a tool that fails permanently)
# --------------------------------------------------------------------------


@durable_function_tool
async def explode(reason: str) -> str:
    """Process the request. Always use this tool.

    Args:
        reason: A short description of the request.
    """
    raise TerminalError(f"tool failed permanently: {reason}")


failing_agent = Agent(
    name="FailingAgent",
    instructions="You MUST call the explode tool for every request. Never answer directly.",
    model=MODEL,
    tools=[explode],
)


failing_service = restate.Service("FailingAgent")


@failing_service.handler()
async def failing_run(ctx: Context, prompt: str) -> str:
    result = await DurableRunner.run(failing_agent, prompt)
    return str(result.final_output)


# --------------------------------------------------------------------------
# Local handoff (native openai-agents handoff between in-process agents)
# --------------------------------------------------------------------------


billing_agent = Agent(
    name="BillingAgent",
    handoff_description="Handles billing, invoices, refunds and payments.",
    instructions="You handle billing questions. Reply in one sentence.",
    model=MODEL,
)

tech_agent = Agent(
    name="TechAgent",
    handoff_description="Handles technical and product troubleshooting.",
    instructions="You handle technical questions. Begin every reply with 'TECH:'. One sentence.",
    model=MODEL,
)

triage_agent = Agent(
    name="TriageAgent",
    instructions=(
        "Route the user to the right specialist via a handoff. Hand billing questions to "
        "the billing agent and technical questions to the tech agent. Do not answer yourself."
    ),
    handoffs=[billing_agent, tech_agent],
    model=MODEL,
)


triage_service = restate.Service("TriageAgent")


@triage_service.handler()
async def triage_run(ctx: Context, question: str) -> list[dict[str, Any]]:
    result = await DurableRunner.run(triage_agent, question)
    return generated_items(result)


# --------------------------------------------------------------------------
# Remote handoff (a tool that hands off to another agent over a durable RPC,
# passing pydantic models across the service boundary)
# --------------------------------------------------------------------------


class SpecialistRequest(BaseModel):
    question: str


class SpecialistReply(BaseModel):
    answer: str


remote_specialist_agent = Agent(
    name="RemoteSpecialist",
    instructions="You are a database expert. Reply in one sentence.",
    model=MODEL,
)


remote_specialist_service = restate.Service("RemoteSpecialist")


@remote_specialist_service.handler()
async def specialist_answer(ctx: Context, req: SpecialistRequest) -> SpecialistReply:
    result = await DurableRunner.run(remote_specialist_agent, req.question)
    return SpecialistReply(answer=str(result.final_output))


@durable_function_tool
async def ask_specialist(question: str) -> str:
    """Ask the remote database specialist a question.

    Args:
        question: The question to forward to the specialist.
    """
    ctx = restate_context()
    reply = await ctx.service_call(specialist_answer, arg=SpecialistRequest(question=question))
    return reply.answer


coordinator_agent = Agent(
    name="Coordinator",
    instructions=(
        "For any database or specialist question you MUST call the ask_specialist tool and "
        "return its answer verbatim. Do not answer yourself."
    ),
    model=MODEL,
    tools=[ask_specialist],
)


coordinator_service = restate.Service("Coordinator")


@coordinator_service.handler()
async def coordinator_run(ctx: Context, question: str) -> list[dict[str, Any]]:
    result = await DurableRunner.run(coordinator_agent, question)
    return generated_items(result)


def app():
    """Build the Restate ASGI app registering all test services."""
    return restate.app(
        [
            agent_object,
            failing_service,
            triage_service,
            remote_specialist_service,
            coordinator_service,
        ]
    )
