"""Pydantic AI services used by the AI integration tests."""

from __future__ import annotations

import json
import os
import uuid

import restate
from typing import Any
from pydantic import BaseModel
from pydantic_ai import Agent
from pydantic_ai.messages import ModelMessage, ModelMessagesTypeAdapter
from pydantic_ai.models.openai import OpenAIChatModel
from pydantic_ai.providers.openai import OpenAIProvider
from restate import Context, ObjectContext, ObjectSharedContext, TerminalError
from restate.ext.pydantic import PydanticTypeAdapter, RestateAgent, restate_context, restate_object_context

MODEL = OpenAIChatModel(
    "gpt-4o-mini",
    provider=OpenAIProvider(api_key=os.environ.get("OPENAI_API_KEY", "scripted-tests-replace-this-model")),
)
MESSAGE_HISTORY_SERDE = PydanticTypeAdapter(list[ModelMessage])


def generated_messages(result: Any) -> list[dict[str, Any]]:
    """Return all Pydantic AI messages generated by one run."""
    return json.loads(result.new_messages_json())


def serialized_messages(messages: list[ModelMessage]) -> list[dict[str, Any]]:
    return json.loads(ModelMessagesTypeAdapter.dump_json(messages))


weather_base = Agent(
    MODEL,
    instructions=(
        "You are a concise assistant. When the user asks about weather you MUST call get_weather. "
        "Answer in one short sentence per city."
    ),
)


@weather_base.tool_plain
async def get_weather(city: str) -> str:
    """Get the current weather for a city."""
    return f"The weather in {city} is sunny and 22 degrees Celsius."


weather_agent = RestateAgent(weather_base, auto_wrap_tools=False)
agent_object = restate.VirtualObject("PydanticAgentObject")


@agent_object.handler()
async def message(ctx: ObjectContext, prompt: str) -> list[dict[str, Any]]:
    history = await ctx.get("messages", serde=MESSAGE_HISTORY_SERDE) or []
    result = await weather_agent.run(prompt, message_history=history)
    ctx.set("messages", result.all_messages(), serde=MESSAGE_HISTORY_SERDE)
    return generated_messages(result)


@agent_object.handler(kind="shared")
async def get_session_messages(ctx: ObjectSharedContext) -> list[dict[str, Any]]:
    history = await ctx.get("messages", serde=MESSAGE_HISTORY_SERDE) or []
    return serialized_messages(history)


failing_base = Agent(MODEL, instructions="You MUST call explode for every request. Never answer directly.")


@failing_base.tool_plain
async def explode(reason: str) -> str:
    """Process the request and always fail permanently."""
    raise TerminalError(f"tool failed permanently: {reason}")


failing_agent = RestateAgent(failing_base, auto_wrap_tools=True)
failing_service = restate.Service("PydanticFailingAgent")


@failing_service.handler()
async def failing_run(ctx: Context, prompt: str) -> str:
    result = await failing_agent.run(prompt)
    return result.output


billing_agent = RestateAgent(Agent(MODEL, instructions="You handle billing questions. Reply in one sentence."))
triage_base = Agent(
    MODEL,
    instructions=(
        "For billing, invoice, refund, or payment questions you MUST call handoff_to_billing. Do not answer directly."
    ),
)


@triage_base.tool_plain
async def handoff_to_billing(question: str) -> str:
    """Delegate a billing question to the local billing agent."""
    result = await billing_agent.run(question)
    return result.output


triage_agent = RestateAgent(triage_base)
triage_service = restate.Service("PydanticTriageAgent")


@triage_service.handler()
async def triage_run(ctx: Context, question: str) -> list[dict[str, Any]]:
    result = await triage_agent.run(question)
    return generated_messages(result)


class SpecialistRequest(BaseModel):
    question: str


class SpecialistReply(BaseModel):
    answer: str


specialist_agent = RestateAgent(Agent(MODEL, instructions="You are a database expert. Reply in one sentence."))
specialist_service = restate.Service("PydanticRemoteSpecialist")


@specialist_service.handler()
async def specialist_answer(ctx: Context, request: SpecialistRequest) -> SpecialistReply:
    result = await specialist_agent.run(request.question)
    return SpecialistReply(answer=result.output)


coordinator_base = Agent(
    MODEL,
    instructions=(
        "For any database or specialist question you MUST call ask_specialist and return its answer. "
        "Do not answer directly."
    ),
)


@coordinator_base.tool_plain
async def ask_specialist(question: str) -> str:
    """Ask the remote database specialist a question."""
    reply = await restate_context().service_call(specialist_answer, arg=SpecialistRequest(question=question))
    return reply.answer


coordinator_agent = RestateAgent(coordinator_base)
coordinator_service = restate.Service("PydanticCoordinator")


@coordinator_service.handler()
async def coordinator_run(ctx: Context, question: str) -> list[dict[str, Any]]:
    result = await coordinator_agent.run(question)
    return generated_messages(result)


DURABLE_AGENTS = [
    weather_agent,
    failing_agent,
    billing_agent,
    triage_agent,
    specialist_agent,
    coordinator_agent,
]


def app():
    return restate.app(
        [
            agent_object,
            failing_service,
            triage_service,
            specialist_service,
            coordinator_service,
        ]
    )
